version: '3.3'
services:
    mysql_node_project:
        container_name: mysql_node
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myDatabase
            MYSQL_USER: db_user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        expose:
            - "3306"